### ISSUE TITLE
[JOSS review] Automated tests

### ISSUE THREAD

**Issue by rreinecke** [mmhs013/pyMannKendall#5]
Please describe how a user can run the tests. Also add a more detailed description what the tests do.
Having only a quick look at your tests it seems like you just comparing values based on some example series. Please consider writing more robust unit tests. If you need more guidance on this feel free to ask.

**Comment by rreinecke** [comment]
Ok testing is not an easy topic I will try to give a couple of pointers.

So the issue with the test the way you are applying them right now is the following:
*  It is unclear were the numbers that you comparing to came from
*  What if you made a mistake in calculating these numbers?
*  If you used your own software your calculations might be wrong because your software is wrong
*  Without deep knowledge about the dataset it is not possible for somebody else to understand the numbers that you are comparing to
*  What if in the future a collaborator would like to add support for lets say pandas which is a great package. And relies on that your tests are testing the core functionality of your system including being able to detect wrong data types etc. 

All in all you should think about replacing the currents tests. Yes I get they can be helpful for you in the beginning but as soon as you compare to a number with more than 2 decimal places you are doing something wrong.

1) Think about if it is possible to create an artificial data series with e.g. numpy that has certain characteristics e.g. no trend at all. 1000 values that are all 0. What should the behavior of your library be? Can you create a series with pseudo random values? e.g. by putting them into a sinus like function etc. etc. there are ways to create interesting data sets that somebody else can directly understand because they are based on two lines of code and some math

2) Think about if your tests should check for edge cases. What if the series has only one entry? Is that valid? What about NaN values? Should there be an error message? If so you can test that!

My suggestions:

1) Add a section to the README: How to tun the unit tests, with description

2) Have a look at how scipy is doing it https://github.com/scipy/scipy/tree/master/scipy/stats/tests
and https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt

Or have a look at other packages I'm sure you can improve your tests! Yes it is more work but it will make your software more robust in the end.

**Comment by rreinecke** [comment]
Take your time!

**Comment by mmhs013** [comment]
@rreinecke thanks for your suggestion. According to your suggestion, I already rewrite my test code. I create data with -
- the random same value,
- linearly increasing values with random noise and
- arbitrary values

The results are compared with several R packages like modifiedmk, fume, rkt, trend. Scipy also checks their statistical test with R and Matlab (https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_stats.py). So, I think, this is OK.

I do not clearly understand, how can I add it in my readme file. Because it is only one line to test it.  I find a [package](https://github.com/connorourke/crystal_torture) in JOSS, who added the Tests section in their readme file. So, I simply adopt their approach.

**Comment by rreinecke** [comment]
Great work! I think this is more comprehensible now! Small typo in the description of the testfile ;)
